<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!DOCTYPE tweet_corpus
[
<!ELEMENT tweet_corpus (tweet+)>
<!ELEMENT tweet (text, identity_terms)>
<!ELEMENT text (#PCDATA)>
<!ELEMENT identity_terms (identity_term*)>
<!ELEMENT identity_term (#PCDATA)>
<!ATTLIST tweet_corpus created CDATA #REQUIRED>
<!ATTLIST tweet tweet_id CDATA #REQUIRED>
<!ATTLIST tweet ihs_label CDATA #IMPLIED>
<!ATTLIST identity_term name CDATA #REQUIRED>
<!ATTLIST identity_term category CDATA #IMPLIED>
]>
<tweet_corpus created="11/19/2021">
<tweet ihs_label="Other" tweet_id="1387856653417070592">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1388464099932180484">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1388600325972582402">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="N" tweet_id="1388772730456182787">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Lauterbach
</identity_term>
<identity_term category="?" name="?">
Minister
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1388821298625794053">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
Deutscher
</identity_term>
<identity_term category="?" name="?">
deutsche
</identity_term>
<identity_term category="?" name="?">
Moslem
</identity_term>
<identity_term category="?" name="?">
muslimische
</identity_term>
<identity_term category="?" name="?">
Nazi
</identity_term>
<identity_term category="?" name="?">
Nazis
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1388961666633764869">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Impfgegner
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389195778724347904">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="Politik" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
bisexuell
</identity_term>
<identity_term category="?" name="?">
tri-
</identity_term>
<identity_term category="?" name="?">
quattro-
</identity_term>
<identity_term category="?" name="?">
multisexuell
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389200617885810688">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
moslem
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389300757124587522">
<text>
anonymized
</text>
<identity_terms />
</tweet>
<tweet ihs_label="Other" tweet_id="1389339149254209539">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="Politik" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
#FCKNZS
</identity_term>
<identity_term category="?" name="?">
#AfDrausausdenParlamenten
</identity_term>
<identity_term category="?" name="?">
AfD
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="N" tweet_id="1389355140960894977">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
rechts
</identity_term>
<identity_term category="?" name="?">
speck
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389474946288521219">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
Jennie Kim
</identity_term>
<identity_term category="?" name="?">
Muslim
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389484749442453505">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="Politik" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Generalsekretär
</identity_term>
<identity_term category="Politik" name="?">
SPD
</identity_term>
<identity_term category="Politik" name="?">
AfD
</identity_term>
<identity_term category="Politik" name="?">
AfD
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="B" tweet_id="1389493221848502273">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389498543136722950">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389508825766670336">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Die Grünen
</identity_term>
<identity_term category="?" name="?">
LGBT
</identity_term>
<identity_term category="?" name="?">
Ostdeutsche
</identity_term>
<identity_term category="?" name="?">
Grünen
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389511405196484614">
<text>
anonymized
</text>
<identity_terms />
</tweet>
<tweet ihs_label="Other" tweet_id="1389526091589734404">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Jude
</identity_term>
<identity_term category="?" name="?">
Jude
</identity_term>
<identity_term category="?" name="?">
Jude
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="B" tweet_id="1389550343206416387">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Spahn
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389561026316849152">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Deutschland
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389572343937347584">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Biontech
</identity_term>
<identity_term category="?" name="?">
Geimpfte
</identity_term>
<identity_term category="?" name="?">
AZ
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389573022395285507">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
Kristina Bulle
</identity_term>
<identity_term category="?" name="?">
Procter &amp; Gamble
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Deutschen
</identity_term>
<identity_term category="?" name="?">
#PGDeutschland
</identity_term>
<identity_term category="?" name="?">
Deutschland
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389574242749100038">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
behindert
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="OL" tweet_id="1389576223685230600">
<text>
anonymized
</text>
<identity_terms />
</tweet>
<tweet ihs_label="Other" tweet_id="1389576751634845700">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389581182602469391">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Rechts
</identity_term>
<identity_term category="?" name="?">
Rechte
</identity_term>
<identity_term category="?" name="?">
Mickey Maus
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389581621666385925">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="Politik" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Ali Utlu
</identity_term>
<identity_term category="?" name="?">
Utlu
</identity_term>
<identity_term category="?" name="?">
schwul
</identity_term>
<identity_term category="?" name="?">
homophob
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389583406820904971">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
Laschet
</identity_term>
<identity_term category="?" name="?">
Laschet
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="N" tweet_id="1389583927652896771">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Flüchtling
</identity_term>
<identity_term category="?" name="?">
Deutsch
</identity_term>
<identity_term category="?" name="?">
deutschen
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389587066355322884">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
schwul
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389589179659657219">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
muslim
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389593196737486850">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389593359354843138">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="B" tweet_id="1389595277586309129">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
behindert
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389596963809673218">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
LGBT
</identity_term>
<identity_term category="?" name="?">
Homophob
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389597418635907074">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
Frauen
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389599525296295940">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389600363620225024">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389601167286706177">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Herren
</identity_term>
<identity_term category="?" name="?">
Männer
</identity_term>
<identity_term category="?" name="?">
christlichen
</identity_term>
<identity_term category="?" name="?">
Jesus
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389601676508676097">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
AfD
</identity_term>
<identity_term category="?" name="?">
ÖRR
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389602708437544965">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389605243302862853">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
liberale
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389606395285319681">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
bayerischer
</identity_term>
<identity_term category="?" name="?">
Flüchtling
</identity_term>
<identity_term category="?" name="?">
preußischen
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389607377872330757">
<text>
anonymized
</text>
<identity_terms />
</tweet>
<tweet ihs_label="Other" tweet_id="1389609562177671169">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389610264136388612">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Big Tech
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389610485285281793">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
geimpfte
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="N" tweet_id="1389611530090647552">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Unternehmerin
</identity_term>
<identity_term category="?" name="?">
Speakerin
</identity_term>
<identity_term category="?" name="?">
Bloggerin
</identity_term>
<identity_term category="?" name="?">
Kolumnistin
</identity_term>
<identity_term category="?" name="?">
Behinderten
</identity_term>
<identity_term category="?" name="?">
behindert
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389612352337817604">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
Joshis
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389612419270459394">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
#Deutschland
</identity_term>
<identity_term category="?" name="?">
Deutschland
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389613114467913728">
<text>
anonymized
</text>
<identity_terms />
</tweet>
<tweet ihs_label="OL" tweet_id="1389613181203591172">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389614070194638851">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
Bosniaken
</identity_term>
<identity_term category="?" name="?">
Yugos
</identity_term>
<identity_term category="?" name="?">
islam
</identity_term>
<identity_term category="?" name="?">
yugo
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389616342777704460">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389616853761282056">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Psychiaterin
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389617366888329221">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389617671227035654">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Männer
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="OL" tweet_id="1389618071195770884">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
männer
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="N" tweet_id="1389619851338174467">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
CDU
</identity_term>
<identity_term category="?" name="?">
Abgeordnete
</identity_term>
<identity_term category="?" name="?">
Maaßen
</identity_term>
<identity_term category="?" name="?">
CDU
</identity_term>
<identity_term category="?" name="?">
Abgeordnete
</identity_term>
<identity_term category="?" name="?">
CDU
</identity_term>
<identity_term category="?" name="?">
Abgeordnete
</identity_term>
<identity_term category="?" name="?">
CDU
</identity_term>
<identity_term category="?" name="?">
Abgeordnete
</identity_term>
<identity_term category="?" name="?">
Brinkhaus
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389620467561115651">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Frau
</identity_term>
<identity_term category="?" name="?">
Chebli
</identity_term>
<identity_term category="?" name="?">
Nazi
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="N" tweet_id="1389620721656209409">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="Politik" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="Politik" name="?">
Junge
</identity_term>
<identity_term category="?" name="?">
Bund
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389620927843946507">
<text>
anonymized
</text>
<identity_terms />
</tweet>
<tweet ihs_label="Other" tweet_id="1389620957216657411">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="N" tweet_id="1389620994453671936">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="Politik" name="?">
Merkel
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="N" tweet_id="1389621399900368901">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Autor
</identity_term>
<identity_term category="?" name="?">
Nazi
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="N" tweet_id="1389621799550394372">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="Politik" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Twiter
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="N" tweet_id="1389622241542000640">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Nichtgeimpften
</identity_term>
<identity_term category="?" name="?">
Politiker
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389622754991919119">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389623002476814339">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Inhaber
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="OL" tweet_id="1389623021393092615">
<text>
anonymized
</text>
<identity_terms />
</tweet>
<tweet ihs_label="B" tweet_id="1389623127395741698">
<text>
anonymized
</text>
<identity_terms />
</tweet>
<tweet ihs_label="Other" tweet_id="1389623345528856582">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Simfy
</identity_term>
<identity_term category="?" name="?">
Simfy
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389623435245019141">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389623544523468809">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
rentner
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389623556619833344">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Vertreter
</identity_term>
<identity_term category="?" name="?">
AfD-Vertreter
</identity_term>
<identity_term category="?" name="?">
Lanz
</identity_term>
<identity_term category="?" name="?">
AfD
</identity_term>
<identity_term category="?" name="?">
Frau
</identity_term>
<identity_term category="?" name="?">
Weidel
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389624033516392461">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Afghanen
</identity_term>
<identity_term category="?" name="?">
Afghanistan
</identity_term>
<identity_term category="?" name="?">
AfD
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389624081985806341">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Mann
</identity_term>
<identity_term category="?" name="?">
CDU
</identity_term>
<identity_term category="?" name="?">
SPD
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389632438360489985">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Reinigungskräfte
</identity_term>
<identity_term category="?" name="?">
Verkäufer
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389639722604052483">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
muslim
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389640177539297281">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389640856676835330">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389650057524285445">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Flüchtling
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="OL" tweet_id="1389653286937153543">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
8ball
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389654617164861445">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
Männer
</identity_term>
<identity_term category="?" name="?">
Frauen
</identity_term>
<identity_term category="?" name="?">
bisexuell
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389657091846156294">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
#Moderna
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="N" tweet_id="1389660327156006912">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
Springer
</identity_term>
<identity_term category="?" name="?">
</identity_term>
<identity_term category="?" name="?">
Journalist
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389663140552511495">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389663717458161667">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
schwul
</identity_term>
</identity_terms>
</tweet>
<tweet ihs_label="Other" tweet_id="1389675586424090626">
<text>
anonymized
</text>
<identity_terms>
<identity_term category="?" name="?">
@USER
</identity_term>
<identity_term category="?" name="?">
@USER